<!DOCTYPE html>
<html lang="fr-ca">
  
  <head>
    <title>Bulle</title>
    <meta name="author" content="Mathieu Huot" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />

    <!-- favicon -->
    <link rel="icon" type="image/png" href="../medias/fav.png" size="16x16" />
    <link rel="icon" type="image/png" href="../medias/fav_32.png" size="32x32" />
    <link rel="icon" type="image/png" href="../medias/fav_96.png" size="96x96" />

    <!-- page description -->
    <meta name="description" content="Présentation de l'entreprise fondée par Marie-Claude Pilon offrant des cours de natation pour les enfants à partir de trois mois. Bulle offre aussi le massage en eau chaude et le massage sur table. L'entreprise familiale se démarque par la qualité de l'eau de son bassin d'eau chaude et l'ambiance chaleureuse de son lieu."/>

    <!-- open graph protocol -->
    <meta property="og:title" content="Bulle" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="description" content="Présentation de l'entreprise fondée par Marie-Claude Pilon offrant des cours de natation pour les enfants à partir de trois mois. Bulle offre aussi le massage en eau chaude et le massage sur table. L'entreprise familiale se démarque par la qualité de l'eau de son bassin d'eau chaude et l'ambiance chaleureuse de son lieu." />
    <meta property="og:url" content="#" />
    <meta property="og:image" content="#" />
    <meta property="og:image:alt" content="description de l'image" />
    
    <!-- css style sheets -->
    <link rel="stylesheet" type="text/css" href="../css/main.css" />
    <link rel="stylesheet" type="text/css" href="../css/acc.css" />
    
    <!-- font awesome style sheet -->
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">

    
    <!-- google fonts "Open Sans", "Quicksand" and "Roboto Mono" -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Quicksand:400,700" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700" />
    
    <!-- external javascript sheet -->
    <script type="text/javascript" src="../javascript/emergessence.js" async></script>
    
  </head>
  <body>
    
    <header id="page-header">
      
      <!-- header logo  -->
      <a href="#"><img src="../medias/bulle.png" alt="logo bulle" id="logo" /></a>

      <!-- icon to display menu on small screen -->
      <div class="icon" onclick="respNav()">&#9776;</div>

    </header>
    
      <!-- header navigation -->
      <nav id="header-nav" class="top-nav top-nav-sticky">
	<a href="#" title="Nos services">Accueil</a>
	<a href="#" title="Inscriptions">Bébé nageur</a>
	<a href="#" title="Rendez-vous">Massothérapie</a>
	<a href="#" title="Nos coordonnées">Nous joindre</a>
      </nav>

    <div id="res-soc-wrapper">
      <a href="https://www.facebook.com/Marie-Claude-Pilon-Massoth%C3%A9rapeute-279507062107384/" target="_blank" title="Suivez-nous"><i class="fab fa-facebook-square fa-2x header-fb"></i></a>
      <a href="#" target="_blank" title="Instagram"><i class="fab fa-instagram fa-2x header-instagram"></i></a>
      <a href="#" target="_blank" title="Courriel"><i class="fas fa-at fa-2x header-email"></i></a>
    </div>
    
    <main role="main">
      
      <div class="card bebe-nageur">
	<h1>Bébé nageur</h1>
	<p class="card__p">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.</p>
	<!--<p>Les inscriptions sont en cours pour la session du : <span>(Date)</span></p>-->
	<a href="#" class="card__a--button">Inscriptions</a>
      </div>
      
      <div class="card massage">
	<h1>Massothérapie</h1>
	<p class="card__p">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.</p>
	<a href="#" class="card__a--button">Rendez-vous</a>
      </div>

      <article class="article marie-claude">
	<h1 class="article__h1">La mère</h1>
	<img src="../medias/mc.jpg" alt="Marie-Claude Pilon" class="article__img" />
	<p class="article__p">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.</p>
      </article>
      <article class="article joanie">
	<h1 class="article__h1">La fille</h1>
	<img src="../medias/joanie.jpg" alt="Joanie Pilon-Proulx" class="article__img" />
	<p class="article__p">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.</p>
      </article>
      
    </main>
    <footer id="page-footer">

      <section class="footer-section liens-utiles">
	<h1><i class="fas fa-share-alt"></i>Liens utiles</h1>
      </section>
      
      <section class="footer-section reseaux-sociaux">
	<a href="https://www.facebook.com/Marie-Claude-Pilon-Massoth%C3%A9rapeute-279507062107384/" target="_blank" title="Suivez-nous"><i class="fab fa-facebook-square fa-3x foo-res-soc-icon"></i></a><a href="#" target="_blank" title="Instagram"><i class="fab fa-instagram fa-3x foo-res-soc-icon"></i></a>
      </section>
      
      <address class="footer-section contact">
	<h1><i class="far fa-address-book"></i> Contact</h1>
	762 avenue Lavallée<br>
	Laval (Québec) H7E 2W7<br>
	<a href="mailto:info@bulle.ca" class="email">info@bulle.ca</a><br>
	450 666-7777
      </address>
      
    </footer>
    
  </body>
</html>
